### PR TITLE
Uninstall ForestAdmin

### LINKED ISSUE #323: Uninstall Forest Admin
# Feature
## Why is this feature being added?

This PR added Forest admin: https://github.com/OperationCode/operationcode_backend/pull/283

It needs to be uninstalled, as we are using ActiveAdmin instead.  Here are the instructions to uninstall forestadmin:

https://doc.forestadmin.com/knowledge-base.html#uninstall
## What should your feature do?

- [ ] Clean uninstall of ForestAdmin and everything from https://github.com/OperationCode/operationcode_backend/pull/283

### PR DESCRIPTION
**Pull request by kirbygit**
# Description of changes

- Completely uninstall gem 'forest_liana' dependencies
- removed Forest routes in config/routes.rb
- removed forest_liana.rb in initializers
- run make bundle to update dependencies

# Issue Resolved

Fixes #323

# Test Still Failed
```
Step 1/11 : FROM ruby:2.3.3
 ---> 0e1db669d557
Step 2/11 : RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
 ---> Using cache
 ---> 87bd5341a922
Step 3/11 : ENV APP_HOME /app
 ---> Using cache
 ---> 051e6d2ff49b
Step 4/11 : RUN mkdir $APP_HOME
 ---> Using cache
 ---> ef99fbf3dd1b
Step 5/11 : WORKDIR $APP_HOME
 ---> Using cache
 ---> cdb491ddd05a
Step 6/11 : ADD Gemfile $APP_HOME/
 ---> Using cache
 ---> 06c4b222e2eb
Step 7/11 : ADD Gemfile.lock $APP_HOME/
 ---> Using cache
 ---> 14bee8451e6e
Step 8/11 : ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile   BUNDLE_JOBS=2   BUNDLE_PATH=/bundle
 ---> Using cache
 ---> 2bf0b3037c44
Step 9/11 : RUN bundle install --system
 ---> Running in 9168e7b02ddd
Warning: the running version of Bundler (1.14.6) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (3/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (4/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most
likely your system doesn't have the CA certificates needed for verification. For
information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
without using SSL, edit your Gemfile sources and change 'https' to 'http'.
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install --system' returned a non-zero code: 17
make: *** [bg] Error 1
```

### CODE REVIEW

**Comment by kirbygit** [comment]
```
Your lockfile was created by an old Bundler that left some things out.
You can fix this by adding the missing gems to your Gemfile, running bundle install, and then removing the gems from your Gemfile.
```

**Comment by hpjaj** [comment]
I am not sure why you are bumping into these issues.  I tried it myself, to make sure it is safely removable:

https://github.com/OperationCode/operationcode_backend/pull/331

**Comment by kirbygit** [comment]
thats odd

**Comment by hpjaj** [comment]
Let me know if you'd like to keep this open, or instead we can merge https://github.com/OperationCode/operationcode_backend/pull/331 ?

**Comment by kirbygit** [comment]
I will redo it in my linux machine. That is strange right? I did that on my mac but I do not know why I am having those issues

**Pull request closed without merging**
