### PR TITLE
Create native setup instructions

### LINKED ISSUE #278: Instructions on a native setup added to the readme
# Feature
## Why is this feature being added?

When using this repo locally, you can do so via Docker, a AWS VM, or through a native setup.  We currently have instructions for the first two, but not the latter.

## What should your feature do?
Create a set of instructions for setting up this repo natively.  Follows the pattern laid out in https://github.com/OperationCode/operationcode_backend/pull/277

### PR DESCRIPTION
**Pull request by aamarill**
# Description of changes
Create native setup instructions to help new users get started easily and quickly. 

# Issue Resolved
Fixes #278

### CODE REVIEW

**Comment by aamarill** [comment]
Created the PR with the hopes of receiving some feedback and advice on my current plan and issues. Specifically, I am currently stuck when I run `rake db:seed`. I'll be troubleshooting this tomorrow and uploading screenshots if I cannot resolve it. 😄

**Comment by nagano564** [comment]
@aamarill the command to run for seeding in our docker file is `make db_seed` You can find all the commands in the `Make` file

**Comment by aamarill** [comment]
Ok, I think the process could be streamlined. But, it now contains all of the steps necessary. The only step that needs to be sorted out is seeding the database. 

When I run 
```shell
$ bin/rake db:seed
```

I get the following error:
screen shot 2018-05-25 at 12 31 21 pm

**Comment by hpjaj** [comment]
@aamarill - Yeah, Redis needs to be running locally, as well.  Can you pls add instructions to install/setup Redis.  And instructions to have redis running in a separate tab.

**Comment by hpjaj** [comment]
@aamarill - BTW, here is a really good, **maintained**, resource for setting up rails locally:

https://gorails.com/setup/osx/10.13-high-sierra

It would be great if we could somehow incorporate this, with references unique to our setup (i.e. our ruby version, rails version, database type, etc.)

**Comment by aamarill** [comment]
@hpjaj I apologize for the delay on this!
If you see someone else looking for work, please have them give me a hand with this. 
I don't think I am going to have too much spare time in the coming weeks 😓

**Comment by wimo7083** [comment]
Going to merge this and work on it a little bit.

**Pull request merged**
