### PR TITLE
Feature/112 case insensitive state by location

### LINKED ISSUE #112: Allow case insensitive search for states in users/by_location
# Feature
## Why is this feature being added?

States are always stored in the DB as uppercase but our current search is case sensitive.

## What should your feature do?
Allow the endpoint /api/v1/users/by_location to accept states case if they're passed in uppercase or lowercase. 

The following queries should return the same number of users.
/api/v1/users/by_location?state=NY
/api/v1/users/by_location?state=ny

### PR DESCRIPTION
**Pull request by hpjaj**
# Description of changes
Allows the endpoint `/api/v1/users/by_location` to accept states case if they're passed in uppercase or lowercase.  Specifically:
- Upcases incoming API params for `/api/v1/users/by_location` endpoint
- Updates all associated specs and documentation  

# Issue Resolved
Fixes #112

### CODE REVIEW

**Comment by hpjaj** [comment]
@rickr - You sure you don't want to refactor this [`before_save` callback](https://github.com/OperationCode/operationcode_backend/pull/114/commits/9b87e38c85404c75553de261d2f72399802e6bfd) to be `upcase_state`, to mitigate against edge case bad data?

**Comment by hpjaj** [comment]
@rickr - there are no indications in the travis output as to why this is failing?

**Comment by hpjaj** [comment]
@rickr - Need anything else on this one?

**Comment by rickr** [comment]
Oh - I'm really sorry. For some reason my comment didn't make it to github. Do you mind doing an upcase in `before_save`? That's a great idea.

**Comment by hpjaj** [comment]
@rickr - No worries.  

Added in the callback, and rebased on master.  All green.  Ready for you.

**Pull request merged**
