### PR TITLE
Feature/175 admin dashboard

### LINKED ISSUE #175: Research: Make it easier to query our database for user information
# Feature
## Why is this feature being added?

Make it easier to query our database for user information

## What should your feature do?
Creates an admin dashboard that is only accessible to specific users.  

- [x] On the `User` page, it should provide a broad filtering mechanism to query for any number of one-off criteria, based on the `User` tables attributes
- [x] Can create, edit, view and/or delete `User`s
- [x] Can create, edit, view and/or delete `AdminUser`s

On the `User` page, it should be able to filter users by:
- [x] mentor
- [x] state
- [x] verified status

On the main dashboard, it should display
- [x] How many users today
- [x] How many users over last week
- [x] How many users over last month
- [x] How many users over last year
- [x] Number of verified users

Future feature: We’d need to define regions, then filter by those on the `User` page

### Background

Was looking at some dashboards for this
https://www.forestadmin.com/

### PR DESCRIPTION
**Pull request by hpjaj**
# Description of changes

Creates an admin dashboard using [ActiveAdmin](https://activeadmin.info/index.html).

- [x] On the `User` page, it should provide a broad filtering mechanism to query for any number of one-off criteria, based on the `User` tables attributes
- [x] Can create, edit, view and/or delete `User`s
- [x] Can create, edit, view and/or delete `AdminUser`s

On the `User` page, it should be able to filter users by:
- [x] mentor
- [x] state
- [x] verified status
- [x] tag name

On the main dashboard, it should display
- [x] How many users today
- [x] How many users over last week
- [x] How many users over last month
- [x] How many users over last year
- [x] Number of verified users

On a `User`'s show page:
- [x] A button that tags/un-tags the user with "community leader"

# Issue Resolved

Fixes #175

### CODE REVIEW

**Comment by hpjaj** [comment]
@hollomancer - Here is how to test it:

```
make bundle
make db_migrate
make db_seed
make
```
- visit `http://localhost:3000/admin/login`
- login: `admin@example.com`
- password: `password`

**Comment by hollomancer** [comment]
Looks good, @hpjaj! We'll need to secure this admin login pretty well.

**Comment by hpjaj** [comment]
@hollomancer - That shouldn't be an issue.  Once this is live in prod, you can create the first `AdminUser` manually in prod's `rails console`.

At that point, you will be the only admin user.  Then you will have the ability to create any others, should you choose to do so.

**Comment by hpjaj** [comment]
@hollomancer - If you pull down the current version of this PR, you can now test for:

### Tagging/un-tagging a user as a 'Community Leader'
- in the user index page, click the **view** link for any user
- click the **Community Leader** button to add the tag
- if they already have the tag, the button will read **Remove Community Leader**

### Filtering by tag
- in the user index page, find the **Tagged With** filter
- choose the appropriate tag
- click **filter**
- returns a list of users that have the selected tag

**Pull request merged**
