### PR TITLE
Feature/aggregated GitHub stats endpoint

### LINKED ISSUE #79: API endpoint for aggregated open source contribution statistics
# Feature
## Why is this feature being added?
We need to better demonstrate the impact that our organization has on the open source community. I would like to see a page showing our members on Github, what they have created, and how the Operation Code organization has enabled that.
## What should your feature do?
MVP: Use Github's API to retrieve statistics on contributions to /OperationCode/foo repositories, and consolidate into a single database.

Corresponding issue for data visualization in the frontend repository - https://github.com/OperationCode/operationcode_frontend/issues/231

### PR DESCRIPTION
**Pull request by hpjaj**
# Description of changes
The purpose of this PR is to:

> Use Github's API to retrieve statistics on contributions to /OperationCode/foo repositories, and consolidate into a single database.

To that end, I have created a library that:

- Hits [GitHub's REST API  v3](https://developer.github.com/v3/)
- Gets all of our:
  - merged pull requests, associated commits and associated GitHub users
  - closed issues and associated GitHub users
  - across all of our repositories
- Converts GitHub's disparate data into a common, calculable, reusable format
- Saves the formatted data to a new `GitHubStatistic` table
- Saves the associated users to a new `GitHubUser` table
- Creates a combination of queries and methods that aggregate and calculate customer facing statistics, namely:
  - totals across all OC repos
  - totals by repository
  - totals for a given GitHub user
  - OC averages
  - totals for a given user, in a given repository
- Creates five new endpoints for our frontend to consume these calculated statistics
- Mitigates against GitHub's API rate limits
- Accounts for GitHub's API constraints around limiting results per page to 100 items
- Deals with GitHub's authentication requirements
- Reduces API hits by querying for records that have been merged since the last record we have in our db
- Offers flexibility to extend the library as our need for new statistics grows
- Incorporates the VCR gem for HTTP related test coverage
- Rake task for fetching data from GitHub's API

### TODO

- [x] Test coverage on remaining library classes
- [x] Deal with error cases from `raise`s, `!`s, etc.
- [x] Update apiary docs

# Issue Resolved
Fixes #79

### CODE REVIEW

**Comment by sethbergman** [comment]
What is needed on the frontend for this awesome feature? I've seen this implemented with koa quite well using `fetch` and some `async` /  `await`, however the only implementations I've found use MongoDB or GraphQL or both. What are going to be some challenges you foresee using this method for aggregation as far as the frontend goes?

**Comment by hpjaj** [comment]
@sethbergman - Good question.  Currently there are five endpoints that the frontend can hit, that will return JSON statistics data.  For example:

`/api/v1/git_hub_statistics/totals` would return something like:

```ruby
{
  "total_repositories": 4,
  "total_closed_pull_requests": 144,
  "total_open_issues": 0,
  "total_commits": 475,
  "total_users": 31,
  "total_additions": 43848,
  "total_deletions": 35676
}
```

`/api/v1/git_hub_statistics/by_repository` would return something like:

```ruby
{
  "operationcode": {
    "total_closed_pull_requests": 2,
    "total_open_issues": 0,
    "total_commits": 8,
    "total_users": 2,
    "total_additions": 3,
    "total_deletions": 3
  },
  "operationcode_backend": {
    "total_closed_pull_requests": 32,
    "total_open_issues": 0,
    "total_commits": 122,
    "total_users": 13,
    "total_additions": 5942,
    "total_deletions": 359
  },
  "operationcode_frontend": {
    "total_closed_pull_requests": 100,
    "total_open_issues": 0,
    "total_commits": 334,
    "total_users": 21,
    "total_additions": 37806,
    "total_deletions": 35127
  },
  "operationcode_bot": {
    "total_closed_pull_requests": 10,
    "total_open_issues": 0,
    "total_commits": 11,
    "total_users": 6,
    "total_additions": 97,
    "total_deletions": 187
  }
}
```

`/api/v1/git_hub_statistics/for_user?git_hub_login=rickr` would return something like:

```ruby
{
  "total_closed_pull_requests": 23,
  "total_open_issues": 0,
  "total_commits": 11,
  "total_additions": 1248,
  "total_deletions": 408
}
```

`/api/v1/git_hub_statistics/user_in_repository?git_hub_login=rickr&repository=operationcode_backend` would return something like:

```ruby
{
  "total_closed_pull_requests": 4,
  "total_open_issues": 0,
  "total_commits": 7,
  "total_additions": 458,
  "total_deletions": 27
}
```


`/api/v1/git_hub_statistics/averages` would return something like:

```ruby
{
  "average_commits_per_user": 15.32258064516129,
  "average_closed_prs_per_user": 4.114285714285714
}
```

Every endpoint also has an optional set of date range params that can be passed in:  `start_date` and/or `end_date`.  They are not required, and default to `start_date: '1970-01-01', end_date: Date.today`.  This allows the frontend to get any set of data for a particular time period (i.e. this month, last month, last quarter, last year, March 2016, etc.)

From there, the frontend would be at liberty to present the data as it sees fit.  The nice thing about this is that the frontend is querying the backend.  It is **not** querying directly against GitHub's API.  Meaning every click, from every user, on every page visit, is not pinging GitHub's API, going against our rate limit, and stifling our site's performance.

There will be a daily cron job that the backend will run that will pull recent data from GitHub's API every morning.  So the data we are presenting to the end user is current (not up to the minute, but as recent as every morning).

Lastly, these five endpoints are the initial batch of calculations that I came up with, based on what GitHub offers, and what we might want.  This is, of course, just a starting off point.  We can open the discussion up to other stats that we might be able to get.  Stats that make sense for us to present, based on the use cases we come up with.  

To that end, here is what one `GitHubUser` database record contains:

```ruby
#<GitHubUser:0x007fc7c326fe70> {
  :id            => 23,
  :user_id       => nil,
  :git_hub_login => "hollomancer",
  :avatar_url    => "https://avatars3.githubusercontent.com/u/9288648?v=4",
  :api_url       => "https://api.github.com/users/hollomancer",
  :html_url      => "https://github.com/hollomancer",
  :git_hub_id    => 9288648,
  :created_at    => Thu, 24 Aug 2017 01:26:44 UTC +00:00,
  :updated_at    => Thu, 24 Aug 2017 01:26:44 UTC +00:00
}
```

And here is what one `GitHubStatistic` database record contains:

```ruby
#<GitHubStatistic:0x007fc7c57d8db0> {
  :id              => 75,
  :git_hub_user_id => 25,
  :source_id       => "137786718",
  :source_type     => "PullRequest",
  :state           => "closed",
  :additions       => 2,
  :deletions       => 2,
  :repository      => "operationcode_backend",
  :url             => "https://github.com/OperationCode/operationcode_backend/pull/152",
  :title           => "RE #123 added 'Operation Code' to subject for password reset and Devi…",
  :number          => "152",
  :completed_on    => Mon, 28 Aug 2017,
  :created_at      => Fri, 01 Sep 2017 01:07:48 UTC +00:00,
  :updated_at      => Fri, 01 Sep 2017 01:07:48 UTC +00:00
}
```

So based on this, the backend could also serve up lots of individual information.  For example,

- `url`s to user's GitHub profiles and avatars
- `url`s to a given pull request, issue or commit
- titles and closed on dates for a given pull request, issue or commit
- and more

This data could also be grouped by certain time period increments (i.e. monthly, quarterly, etc.), which would then provide the frontend with data to create line or bar graphs.  And since we're storing the data in the db, we continue to build a set of analyzable data, with each passing day.

Hope that helps!

**Comment by hpjaj** [comment]
@rickr - I just added the [Whenever gem](https://github.com/javan/whenever) for running cron jobs:  https://github.com/OperationCode/operationcode_backend/pull/153/commits/0f70391c37dc7821212e74bafdd0887d82ed71cd

This is going to benefit not just this issue, but also the [Pull all meetups from the meetup API](https://github.com/OperationCode/operationcode_backend/issues/40) issue that @leenyburger is working on.

I'd like to learn how you would set this up in prod, when you have a chance.  Thanks!

**Comment by rickr** [comment]
I think we can tie in `whenever --update-crontab` into the same script we need to create for #61. Each time the app starts it would update the crontab for us.

**Comment by hpjaj** [comment]
@rickr - A couple questions.  

1.  When you the time comes, can you show me how you do that?
2. Can you pls code review this PR?

Gracias

**Comment by rickr** [comment]
Everything looks good with the exception of setting up whenever. Would you like to include those changes here or open up a new ticket and fix the issue there?

It's pretty simple to do - we'll need a simple shell script and an update to the Dockerfile to call the script instead of the current CMD: (https://github.com/OperationCode/operationcode_frontend/milestone/14)

**Comment by hpjaj** [comment]
Hey @rickr - Apologies for the delayed response!  I have been working on a project for the last week that has  monopolized **all** of my free time. 

You probably already know this, but practically speaking, in order for any of the code in this PR to be of value, we will need that cron job running daily.  Otherwise, the stats will never be pulled for analysis and compilation. 

That said, regarding setting up the Whenever gem, will you be able to write the shell script and update the Docker file, regardless?  

If yes, then whatever is best for you works for me.  Meaning, we can create a new story for it for you to do.  Or you can submit a commit to this PR.  Whatever will get things done fastest.

What would you like to do?

**Comment by hpjaj** [comment]
@rickr - I removed the whenever gem.  I'll create a follow up issue for it. 

I need to complete the apiary docs.  Outside of that, any other changes we'd like to see?

**Comment by hpjaj** [comment]
@rickr - Apiary docs have been updated.  This one is ready.

**Pull request merged**
