### PR TITLE
Update README.md

### LINKED ISSUE #444: add license section in readme
# Feature
## What should your feature do?

--- add license section in readme file

# Bug Report

### PR DESCRIPTION
**Pull request by vyaspranjal33**
added license section in readme

# Description of changes

# Issue Resolved

Fixes #444

### CODE REVIEW

**Comment by wimo7083** [comment]
Thanks for the awesome change.

**Comment by vyaspranjal33** [comment]
@wimo7083 can u please help .. team operationcode is not responded to my email , nor responding to tweets or message on facebook

**Comment by vyaspranjal33** [comment]
@wimo7083 please let me know expected time to respond i will be getting
 as per mentioned in Hacktoberfest image .. contributor who will close 3 issues will be eligible for getting tshirt , i've made PRs which helped in resolving issues

**Comment by wimo7083** [comment]
This has been forwarded to @kylemh . Thank you.

**Pull request merged**
